//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemo_test_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public Nullable<int> id_Patient { get; set; }
        public Nullable<int> id_Doctor { get; set; }
        public Nullable<int> id_Study { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> EndPrice { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Study Study { get; set; }
    }
}
